version: "2"
exclude_patterns:
  - "src/__tests__/"
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/src/utils/SampleData.js"
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 100 # for the sake of functional components and their 'markup'
  nested-control-flow:
    config:
      threshold: 5
  return-statements:
    config:
      threshold: 5
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
